# See https://github.com/actions-rs/audit-check
name: Security audit
on:
  schedule:
    - cron: '0 0 */7 * *'
jobs:
  security_audit:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
